### PR TITLE
Add io class for Noritake CU-U Series VFD (in serial mode)

### PR DESCRIPTION
**Pull request by btb**
These VFDs are HD44780 compatible, with the normal parallel interface, as well as an spi-like serial interface. This class enables the serial mode.

### CODE REVIEW

**Comment by btb** [comment]
Sure. I didn't put a link in because it looks like you can't download datasheets from Noritake without giving them contact info first. I found a good pointer URL to use anyway though (https://www.noritake-elec.com/products/vfd-display-module/character-display/cu-u-series). And I just discovered the application note, which describes the interface better anyhow. (https://noritake-elec.com/includes/documents/brochure/CU-U_Application_Note.pdf)
I'll work on this some more.

**Comment by bperrybap** [comment]
I've run into that with Noritake as well. Then once give the contact information, they end up contacting you a few times even after you tell them all you wanted was a datasheet.

**Comment by btb** [comment]
Also, this seems like it might be considered a "3-Wire SPI" device, do you think it's worth it to try to make it work using the hardware SPI pins?

**Comment by bperrybap** [comment]
It isn't difficult to use h/w SPI when possible. Take a look at the i/o class for the NTCU165ECPB.
It is only a few simple conditional checks to use SPI h/w when possible or revert back to bit banging functions when it isn't.

The trickier part is the examples, as the examples need to work out of the box on all h/w.
Leaonardo is pretty messed up and can't use the h/w SPI SS pin since they didn't hook it up to a pin on a header.

**Comment by btb** [comment]
I tried all the examples and all worked great on the VFD I have (CU20045-UW5A) - the only library feature missing appears to be cursor() and noCursor() which seems consistent with the datasheet for that model. It's possible others in the series would support it.

**Comment by btb** [comment]
Yeah, I just picked those pins based on Noritake's sample code, that makes a lot more sense, especially now that I got SPI working.

**Comment by bperrybap** [comment]
Is all of this working now? All the examples etc?
I'm about to merge it in.
There will be some tweaks, since I've moved the CustomChar sketch out of the hd44780 examples and down into i/o class example. (This has already been but is on an uncommitted branch)

**Comment by bperrybap** [comment]
Specifically, I want to make sure that hd44780 examples like LCDiSpeed, and LCDlibTest are working.
Well, working as well as the h/w works as some of the h/w does not have things like cursors.
How about things like display(), noDisplay(), on(), off() ?Do they turn the display "pixels" on/off?

**Comment by btb** [comment]
Yes, they are all working.

**Pull request merged**
